[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "F8t3bFx5Dug3Po2ptW87JB6KDmgUBHQhDuwjeicQraAz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
hello_anchor = "F8t3bFx5Dug3Po2ptW87JB6KDmgUBHQhDuwjeicQraAz"

[idl]
out = "target/idl"