[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "3nantEanKHuNfXSY3uCXEPJsQqJDaSjbLEKZjWLtHeG7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/c/Users/rajva/Desktop/wallet/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
